language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: iQ0CY536jA43yO5s1VSWkUFxiJ76JZ57m0uJLWrblNhrKnLHROt386J0hlmrbfen5PfUOQcn1oyb4/zaX0HInW+bAX91lP+t00Y395L48BmYLQdbzmTLjJ0W3+S/NxSVHvLTrzGfhUwM/kf7EX/E603ZwPLKuGy5UMcv1XdqG/Q8KHomrYyd+p/t9/I/mrx8taE6Gl/81DRfEHsnrA0ArluxYvitQSdaBw63lPiQ059ALCSRJEKxxEU5eCOVj6BClniQFcTBfnyhnGug8j5GbGJjyiqfnrd+BICbH6sSYtzxgXymoBtWSNMdTdFe3DsL5oM+0jVan7JgjVWumW/hojHoBPThpeWtwivB0f+sKXPOXPKht7qFOdVccHzfz/vJEb4Hrel8A0X6njBAv7LBaYOzK+lcFU7ml/7W7vH7wGR0xNF2q3KrfP+TPJxsdUzk8mzakJ1NCPT+bAQc1hGGHgfMwjoP6r7yGaBehqssILF/k+uwB2tFvhHemaSOHdny1erHplkGVDA4kjdst2LOT6px33zjUepIMYumfIE1RMqDgoGFWvp6CG8emP2a1xhVLpoqvsXemuninNIx3P42l0AncyutFDskhzHQokE+5E/EA5xD8ZTm+GD/8MH5WpIeHoEswSVehvJjnT4XtyTha5bnvKez01F0mePIiDlgzYc=
  app: myhealthnavigator
  skip_cleanup: true
